"""Task management API — backed by the real Agent runtime (Planner + RetryableDAGExecutor)."""

import uuid
from datetime import datetime
from typing import Any, Dict, Optional

from fastapi import APIRouter, HTTPException, status
from pydantic import BaseModel, Field

router = APIRouter()

# ── Lazy Agent singleton (same pattern as chat.py) ─────────────────────────
_agent = None


def _get_agent():
    """Return a module-level Agent singleton with tools registered."""
    global _agent
    if _agent is not None:
        return _agent

    import os

    from core.agent import Agent, AgentConfig

    config = AgentConfig(
        model=os.environ.get("LLM_MODEL", "gpt-4o"),
        provider=os.environ.get("LLM_PROVIDER", "openai"),
        api_key=os.environ.get("OPENAI_API_KEY") or os.environ.get("ANTHROPIC_API_KEY"),
        api_base=os.environ.get("OPENAI_API_BASE"),
        max_steps=int(os.environ.get("POLARIS_MAX_STEPS", "20")),
    )

    _agent = Agent(config=config)

    try:
        from tools.registry import ToolRegistry

        r = ToolRegistry()
        r.register_all()
        _agent.register_tools_from_registry(r)
    except ImportError:
        pass

    return _agent


# ── Models ──────────────────────────────────────────────────────────────────


class TaskCreateRequest(BaseModel):
    """Request to create a new task."""

    goal: str = Field(..., description="Task goal / description")
    context: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Context for the task")
    options: Optional[Dict[str, Any]] = Field(default_factory=dict, description="Optional overrides")
    agent_config: Optional[Dict[str, Any]] = Field(None, description="Per-task agent config overrides")


class TaskUpdateRequest(BaseModel):
    """Request to update task state."""

    status: Optional[str] = Field(None, description="New task status")
    context: Optional[Dict[str, Any]] = Field(None, description="Updated context")


class TaskResponse(BaseModel):
    """Task status response."""

    task_id: str = Field(..., description="Unique task ID")
    goal: str = Field("", description="Task goal")
    status: str = Field("created", description="created | planning | running | completed | failed")
    progress: float = Field(0.0, ge=0.0, le=100.0, description="Progress percentage")
    plan: Optional[Dict[str, Any]] = Field(None, description="Generated plan tree")
    result: Optional[Dict[str, Any]] = Field(None, description="Execution result")
    error: Optional[str] = Field(None, description="Error message if failed")
    steps_completed: int = Field(0, description="Number of completed steps")
    total_time_ms: float = Field(0.0, description="Execution time in milliseconds")
    created_at: datetime = Field(default_factory=datetime.now)
    updated_at: datetime = Field(default_factory=datetime.now)


# ── In-memory store (resilient across requests, lost on restart) ───────────
task_store: Dict[str, Dict[str, Any]] = {}


def _serialize_plan(plan_tree) -> dict:
    """Serialize a PlanTree to a JSON-safe dict."""
    if hasattr(plan_tree, "model_dump"):
        return plan_tree.model_dump()
    if hasattr(plan_tree, "dict"):
        return plan_tree.dict()
    return {"id": getattr(plan_tree, "id", "unknown"), "content": str(plan_tree)}


# ── Endpoints ──────────────────────────────────────────────────────────────


@router.post("/", status_code=status.HTTP_201_CREATED)
async def create_task(body: TaskCreateRequest):
    """Create a task with a real plan generated by the LLM Planner.

    Stores the generated PlanTree for later execution.
    """
    agent = _get_agent()
    task_id = f"task-{uuid.uuid4().hex[:8]}"
    now = datetime.now()

    # Generate a real execution plan
    try:
        plan_tree = agent.planner.generate_plan(body.goal, body.context or {})
        plan_dict = _serialize_plan(plan_tree)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=f"Plan generation failed: {exc}")

    entry = {
        "task_id": task_id,
        "goal": body.goal,
        "status": "created",
        "progress": 0.0,
        "plan": plan_dict,
        "plan_id": plan_dict.get("id", "unknown"),
        "result": None,
        "error": None,
        "steps_completed": 0,
        "total_time_ms": 0.0,
        "created_at": now,
        "updated_at": now,
    }
    task_store[task_id] = entry
    return entry


@router.get("/{task_id}", status_code=status.HTTP_200_OK)
async def get_task(task_id: str):
    """Get task status and results."""
    if task_id not in task_store:
        raise HTTPException(status_code=404, detail="Task not found")
    return task_store[task_id]


@router.get("/", status_code=status.HTTP_200_OK)
async def list_tasks(
    limit: int = 10,
    offset: int = 0,
    status_filter: Optional[str] = None,
):
    """List tasks, optionally filtered by status."""
    tasks = list(task_store.values())
    if status_filter:
        tasks = [t for t in tasks if t["status"] == status_filter]

    tasks_slice = tasks[offset : offset + limit]
    return {
        "data": tasks_slice,
        "pagination": {
            "page": offset // limit + 1 if limit else 1,
            "size": limit,
            "total": len(tasks),
            "pages": max(1, (len(tasks) + limit - 1) // limit) if limit else 1,
        },
    }


@router.put("/{task_id}", status_code=status.HTTP_200_OK)
async def update_task(task_id: str, body: TaskUpdateRequest):
    """Update task metadata."""
    if task_id not in task_store:
        raise HTTPException(status_code=404, detail="Task not found")

    entry = task_store[task_id]
    if body.status:
        entry["status"] = body.status
    if body.context:
        entry["plan"]["context"] = body.context
    entry["updated_at"] = datetime.now()
    return entry


@router.delete("/{task_id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_task(task_id: str):
    """Delete a task."""
    if task_id not in task_store:
        raise HTTPException(status_code=404, detail="Task not found")
    del task_store[task_id]
    return None


@router.post("/{task_id}/execute", status_code=status.HTTP_200_OK)
async def execute_task(task_id: str):
    """Execute a task using the real Agent runtime (full OODA loop).

    The Agent internally uses the Planner + RetryableDAGExecutor with
    circuit breaker, retry, and dead-letter queue.
    """
    if task_id not in task_store:
        raise HTTPException(status_code=404, detail="Task not found")

    entry = task_store[task_id]
    entry["status"] = "running"
    entry["progress"] = 10.0
    entry["updated_at"] = datetime.now()

    agent = _get_agent()
    goal = entry["goal"]
    context = entry.get("plan", {}).get("context", entry.get("plan", {}))

    import time

    start = time.monotonic()
    try:
        result = await agent.run(goal, context)
        elapsed = (time.monotonic() - start) * 1000

        entry["status"] = "completed"
        entry["progress"] = 100.0
        entry["result"] = {
            "success": result.success,
            "summary": result.summary,
            "steps": len(result.steps),
            "tool_calls": result.tool_calls,
            "plan_id": getattr(result, "plan_id", None),
            "tokens_used": getattr(result, "tokens_used", 0),
        }
        entry["steps_completed"] = len(result.steps)
        entry["total_time_ms"] = round(elapsed, 1)
    except Exception as exc:
        elapsed = (time.monotonic() - start) * 1000
        entry["status"] = "failed"
        entry["progress"] = 100.0
        entry["error"] = str(exc)
        entry["total_time_ms"] = round(elapsed, 1)

    entry["updated_at"] = datetime.now()
    return entry
